---
- name: Creating map settings
  copy:
    src: "{{ item }}"
    dest: "{{ factorio_full_path }}/data/{{ item }}"
    owner: "{{ factorio_user }}"
    mode: "0644"
  loop:
  - map-gen-settings.json
  - map-settings.json
  notify:
  - restart factorio

- name: Creating server settings
  template:
    src: server-settings.json.j2
    dest: "{{ factorio_full_path }}/data/server-settings.json"
    owner: "{{ factorio_user }}"
    mode: "0644"
  notify:
  - restart factorio

- name: Creating admin list
  copy:
    content: "{{ factorio_admin_list | to_json }}"
    dest: "{{ factorio_full_path }}/server-adminlist.json"
    owner: "{{ factorio_user }}"
    mode: "0644"
  when: factorio_admin_list
  notify:
  - restart factorio