---
- name: Creating system user
  user:
    name: "{{ factorio_user }}"
    state: present
    shell: '{{ os_nologin_shell_path }}'
    createhome: no
    comment: 'Created by Ansible'
    system: yes

- name: Downloading server files
  unarchive:
    src: "{{ factorio_headless_url }}"
    dest: "{{ factorio_path }}"
    owner: "{{ factorio_user }}"
    remote_src: yes
    validate_certs: "{{ not testing }}"

- name: Creating systemd unit
  template:
    src: systemd.service
    dest: /etc/systemd/system/factorio.service
    owner: root
    group: root
    mode: '0644'