---
# tasks file for factorio
- name: Installing server
  become: yes
  import_tasks: install.yml

- name: Configuring server
  become: yes
  become_user: "{{ factorio_user }}"
  import_tasks: configure.yml