---
# tasks file for factorio
- name: Installing server
  become: yes
  import_tasks: install.yml

- name: Starting server
  become: yes
  when: not factorio_stop_server
  block:
  - name: Configuring server
    become_user: "{{ factorio_user }}"
    vars:
      ansible_remote_tmp: /tmp
    import_tasks: configure.yml

  - name: Copying mods
    become_user: "{{ factorio_user }}"
    import_tasks: mods.yml

  - name: Starting server
    import_tasks: run.yml

- name: Stopping server
  include_tasks: stop.yml
  when: factorio_stop_server