
- name: Stopping server
  become: true
  block:
  - name: Stopping server
    systemd:
      name: factorio
      state: stopped
      daemon_reload: yes
      enabled: no

  - name: Close port on firewall
    community.general.ufw:
      rule: allow
      port: "{{ factorio_port }}"
      proto: udp
      delete: yes