
- name: Stopping server
  become: yes
  block:
  - name: Stopping server
    systemd:
      name: "{{ item }}"
      state: stopped
      daemon_reload: yes
      enabled: no
    loop:
    - factorio
    - factorio.socket

  - name: Close port on firewall
    community.general.ufw:
      rule: allow
      port: "{{ factorio_port }}"
      proto: udp
      delete: yes