---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
- name: instance
  pre_build_image: yes
  image: solita/ubuntu-systemd:latest
  command: /sbin/init
  capabilities:
  - SYS_ADMIN
  - NET_ADMIN
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  host_vars:
    instance:
      ansible_user: ansible
verifier:
  name: ansible
  host_vars:
    instance:
      ansible_user: ansible