---
# This is an example playbook to execute Ansible tests.
- name: Verify as user
  hosts: all
  tasks:
  - name: State main binary
    stat:
      path: "/srv/factorio/bin/x64/factorio"
    register: factorio_binary

  - name: Check if executable exists
    assert:
      that: factorio_binary.stat.executable is true
